name: build ckeck
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - Dockerfile
      - Gemfile
      - Gemfile.lock
jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build Docker image
        run: docker build -t brakeman-action:test .
